apiVersion: admin.rio.cattle.io/v1
kind: PublicDomain
metadata:
  name: auth.rio.dishapp.com
spec:
  targetApp: jwt-server
  targetNamespace: default
---

apiVersion: admin.rio.cattle.io/v1
kind: PublicDomain
metadata:
  name: hasura.rio.dishapp.com
spec:
  targetApp: hasura
  targetNamespace: default
---

apiVersion: admin.rio.cattle.io/v1
kind: PublicDomain
metadata:
  name: worker-ui.rio.dishapp.com
spec:
  targetApp: worker-ui
  targetNamespace: default
---

apiVersion: admin.rio.cattle.io/v1
kind: PublicDomain
metadata:
  name: search.rio.dishapp.com
spec:
  targetApp: search
  targetNamespace: default
---

apiVersion: admin.rio.cattle.io/v1
kind: PublicDomain
metadata:
  name: web.rio.dishapp.com
spec:
  targetApp: web
  targetNamespace: default
---
